version: "3.9"

services:
  postgres:

    image: "postgres:14-alpine"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./database.dev.env
    ports:
      - "5532:5432"
    networks:
      - backend

  pgadmin:
    image: "dpage/pgadmin4:6.21"
    volumes:
      - ./pgadmin-init/servers.json:/pgadmin4/servers.json
      - ./pgadmin-init/pgpass:/pgpass
    env_file:
      - ./database.dev.env
    ports:
      - "5050:80"
    networks: 
      - backend

  keycloak:
    image: "quay.io/keycloak/keycloak:16.1.1"
    env_file:
      - ./keycloak.dev.env
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

